build:
  version: "1.0"
  
accounts:
  message: "Welcome to SubhamBank accounts related prod APIs "
  contactDetails:
    name: "John Doe 3 - L3 Support Lead"
    email: "{cipher}5f990eb40d0a45c99084adee17da94bd7cf7ac7750775617218cc532aadd79aefd912dd10231cc33556c2b2211e7a4a8"
  onCallSupport:
    - (666) 255-1234

    - (666) 543-1345
